#!/usr/bin/env bash
# Canonical runtime env defaults for Ralph orchestrator.
set -euo pipefail

init_ralph_env_defaults() {
  # Core runtime metadata
  RALPH_VERSION="${RALPH_VERSION:-0.1.0}"
  RALPH_PROJECT_DIR="${RALPH_PROJECT_DIR:-}"
  RALPH_GLOBAL_DIR="${RALPH_GLOBAL_DIR:-}"
  RALPH_SCRIPT_DIR="${RALPH_SCRIPT_DIR:-}"
  RALPH_WORKSPACE="${RALPH_WORKSPACE:-}"

  # Configuration overrides (env/profile/CLI are merged elsewhere)
  RALPH_ENGINE="${RALPH_ENGINE:-}"
  RALPH_MODEL="${RALPH_MODEL:-}"
  RALPH_LANG="${RALPH_LANG:-}"
  RALPH_HOOKS_JSON="${RALPH_HOOKS_JSON:-}"
  RALPH_TASKS_JSON="${RALPH_TASKS_JSON:-}"
  RALPH_ALLOW_RALPH_EDITS="${RALPH_ALLOW_RALPH_EDITS:-}"
  RALPH_VERBOSE="${RALPH_VERBOSE:-}"

  # Human guard defaults
  RALPH_HUMAN_GUARD="${RALPH_HUMAN_GUARD:-}"
  RALPH_HUMAN_GUARD_ASSUME_YES="${RALPH_HUMAN_GUARD_ASSUME_YES:-}"
  RALPH_HUMAN_GUARD_SCOPE="${RALPH_HUMAN_GUARD_SCOPE:-}"

  # Issue/chaining defaults
  RALPH_ISSUES_PROVIDERS="${RALPH_ISSUES_PROVIDERS:-}"
  RALPH_CHECKPOINT_ENABLED="${RALPH_CHECKPOINT_ENABLED:-}"
  RALPH_CHECKPOINT_PER_STEP="${RALPH_CHECKPOINT_PER_STEP:-}"

  # Source-control overrides
  RALPH_SOURCE_CONTROL_ENABLED="${RALPH_SOURCE_CONTROL_ENABLED:-}"
  RALPH_SOURCE_CONTROL_BACKEND="${RALPH_SOURCE_CONTROL_BACKEND:-}"
  RALPH_SOURCE_CONTROL_ALLOW_COMMITS="${RALPH_SOURCE_CONTROL_ALLOW_COMMITS:-}"
  RALPH_SOURCE_CONTROL_BRANCH_PER_SESSION="${RALPH_SOURCE_CONTROL_BRANCH_PER_SESSION:-}"
  RALPH_SOURCE_CONTROL_BRANCH_NAME_TEMPLATE="${RALPH_SOURCE_CONTROL_BRANCH_NAME_TEMPLATE:-}"
  RALPH_SOURCE_CONTROL_REQUIRE_TICKET_FOR_BRANCH="${RALPH_SOURCE_CONTROL_REQUIRE_TICKET_FOR_BRANCH:-}"
}
